Repository OpenLitterMap/react-native, pull requests merged in 2021-11, with the labels that each got.

#128 Refactoring to use single array
  actions/gallery_actions.js
  actions/images_action.js
  actions/index.js
  actions/photos_actions.js
  actions/shared_actions.js
  actions/types.js
  actions/web_actions.js
  reducers/gallery_reducer.js
  reducers/images_reducer.js
  reducers/index.js
  reducers/photos_reducer.js
  reducers/shared_reducer.js
  reducers/web_reducer.js
  screens/camera/CameraScreen.js
  screens/gallery/GalleryScreen.js
  screens/gallery/galleryComponents/AlbumList.js
  screens/home/HomeScreen.js
  screens/home/homeComponents/UploadImagesGrid.js
  screens/pages/AddTags.js
  screens/pages/RightPage.js
  screens/pages/components/LitterBottomSearch.js
  screens/pages/components/LitterImage.js
  screens/pages/components/LitterTags.js
  store/index.js
  utils/isGeotagged.js
Labels: For Review

#118 fix: remove legacy string ref
  screens/auth/AuthScreen.js
Labels: For Review

#119 refactor: use immer in auth_reducer
  actions/auth_actions.js
  actions/types.js
  reducers/auth_reducer.js
Labels: For Review

#131 feat: change recommended changes in #129
  actions/images_action.js
  actions/types.js
  actions/web_actions.js
  reducers/images_reducer.js
  screens/gallery/galleryComponents/AlbumList.js
  screens/home/HomeScreen.js
  screens/pages/AddTags.js
  screens/pages/components/LitterBottomSearch.js
Labels: For Review

#132 Add new brands
  actions/litter_actions.js
  assets/data/categories.js
  assets/data/litterkeys.js
  assets/data/xpLevel.js
  assets/langs/ar/litter.json
  assets/langs/de/litter.json
  assets/langs/en/litter.json
  assets/langs/es/litter.json
  assets/langs/fr/litter.json
  assets/langs/nl/litter.json
  assets/langs/pt/litter.json
  reducers/auth_reducer.js
  reducers/litter_reducer.js
  screens/pages/AddTags.js
  screens/pages/components/LitterBottomSearch.js
  screens/pages/components/LitterPickerWheels.js
  screens/pages/data/categories.js
  screens/pages/data/litterkeys.js
Labels: Changes Requested

#130 Single API -- Upload image with tags
  actions/auth_actions.js
  actions/gallery_actions.js
  actions/images_action.js
  actions/litter_actions.js
  actions/settings_actions.js
  actions/shared_actions.js
  actions/types.js
  actions/web_actions.js
  assets/langs/ar/settings.json
  assets/langs/de/settings.json
  assets/langs/en/settings.json
  assets/langs/es/settings.json
  assets/langs/fr/settings.json
  assets/langs/nl/settings.json
  assets/langs/pt/settings.json
  reducers/auth_reducer.js
  reducers/images_reducer.js
  screens/SettingsScreen.js
  screens/camera/CameraScreen.js
  screens/gallery/GalleryScreen.js
  screens/home/HomeScreen.js
  screens/pages/AddTags.js
  screens/pages/components/LitterBottomSearch.js
  screens/userStats/UserStatsScreen.js
Labels: Changes Requested

#135 fix: review changes for #116
  actions/gallery_actions.js
  actions/images_action.js
  screens/home/HomeScreen.js
Labels: Ready to merge

#138 Fix package.json lock
  actions/types.js
  android/app/build.gradle
  android/build.gradle
  ios/Podfile.lock
  ios/openlittermap.d
  ios/openlittermap.dia
  ios/openlittermap.xcodeproj/project.pbxproj
  ios/openlittermap.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  package-lock.json
Labels: bug, For Review
